# Generated by Django 5.1.1 on 2024-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("IDS", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_year", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "linkedin_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "linkedin_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "linkedin_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twitter_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twitter_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("github_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("work_email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_title_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_title_sub_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_title_levels",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_website",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "job_company_founded",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "job_company_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_linkedin_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_linkedin_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_facebook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_twitter_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_locality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_metro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_company_location_geo", models.TextField(blank=True, null=True)),
                (
                    "job_company_location_street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_postal_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "job_company_location_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_company_location_continent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_last_updated",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "job_start_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("job_summary", models.TextField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_locality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_metro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_continent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_postal_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("location_geo", models.TextField(blank=True, null=True)),
                (
                    "location_last_updated",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "linkedin_connections",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "inferred_salary",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "inferred_years_experience",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("phone_numbers", models.TextField(blank=True, null=True)),
                ("emails", models.TextField(blank=True, null=True)),
                ("interests", models.TextField(blank=True, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("location_names", models.TextField(blank=True, null=True)),
                ("regions", models.TextField(blank=True, null=True)),
                ("countries", models.TextField(blank=True, null=True)),
                ("street_addresses", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("profiles", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                ("version_status", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
