# Generated by Django 5.1.1 on 2024-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_person_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
